//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2SIPC2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class othelloEntities1 : DbContext
    {
        public othelloEntities1()
            : base("name=othelloEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<participante> participante { get; set; }
        public virtual DbSet<participanteTorneo> participanteTorneo { get; set; }
        public virtual DbSet<partida> partida { get; set; }
        public virtual DbSet<torneo> torneo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
