//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2SIPC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class participanteTorneo
    {
        public decimal codigoPart { get; set; }
        public string descripcion { get; set; }
        public decimal movimientos { get; set; }
        public string resultado { get; set; }
        public decimal rondas { get; set; }
        public decimal codigoTorneo { get; set; }
        public string usuario { get; set; }
    
        public virtual usuario usuario1 { get; set; }
        public virtual torneo torneo { get; set; }
    }
}
